In [95]:
import Pkg
Pkg.activate("MMLDS_project")

#SINDy
#Pkg.add("DataDrivenDiffEq")
#Pkg.add("DataDrivenSparse")
#Pkg.add("Subscripts")

#RESERVOIR 
#Pkg.update()
#Pkg.instantiate()
#Pkg.add("ProgressMeter")
#Pkg.add("DynamicalSystems")
#Pkg.add("ReservoirComputing")
#Pkg.add("Plots")
#Pkg.add("Printf")
#Pkg.add("DifferentialEquations")
#Pkg.add("OrdinaryDiffEq")
#Pkg.add("NetCDF")
#Pkg.add("JLD2")

#SINDy
using DataDrivenDiffEq
using DataDrivenSparse
using Subscripts

#RESERVOIR
using ProgressMeter
using DynamicalSystems, ReservoirComputing, Plots, Printf
using DifferentialEquations
using OrdinaryDiffEq
using NetCDF
using JLD2

  Activating project at `~/Documents/GitHub/compare_ML_DynamicalSystem/MMLDS_project/src/MMLDS_project`


In [28]:
include("data.jl")
include("SINDy.jl")

train_SINDy (generic function with 3 methods)

In [13]:
#Loading and changing El Nino Data
path_to_data = "sst.mon.mean.nc"

x = ncread(path_to_data, "sst") #sst = Sea Surface Temperature
x_reduced = x[121:170, 86:95, :] #only concerned with the important region for the El Nino happening

X_vector = compress_data_matrix(x_reduced, 5, false, true)

20×2040 Matrix{Float64}:
 28.0325  27.8742  28.1076  28.688   …  28.621   29.4195  29.5172  29.0083
 28.2426  28.2316  28.488   28.9117     28.3489  29.3835  29.6865  29.3908
 28.5179  28.6131  28.8473  29.1355     28.6434  29.723   29.7411  29.3795
 28.84    28.8382  29.0742  29.1841     29.4347  30.2484  29.8994  29.4668
 29.023   28.9616  29.1702  29.2372     29.4146  30.2277  29.8914  29.5535
 29.1572  29.1256  29.2598  29.2776  …  29.7037  30.4001  30.031   29.7284
 29.1264  29.117   29.196   29.2381     29.8099  30.4189  30.0984  29.8489
 28.9993  29.0324  29.076   29.1209     30.1048  30.5088  30.2152  29.9283
 28.7191  28.7542  28.6979  28.8395     30.32    30.6631  30.3864  30.0508
 28.4407  28.3725  28.2181  28.6071     30.32    30.5643  30.4019  30.1978
 28.7257  28.5573  28.5916  28.9932  …  27.2255  28.4254  29.3495  29.8018
 28.7958  28.7403  28.7715  29.102      26.6425  28.0568  29.141   29.8132
 28.8938  28.9374  28.9322  29.1185     27.5829  28.7421  29.3249  29.7972


In [134]:
#shrink the dimensions to see if it is working
#we have to make more basis variables
x_sindy = X_vector[1:3,:]
ddsol = train_SINDy(x_sindy, 4, 1e-1, 0)

ddsol.prob.p[1]


Model ##Basis#418 with 3 equations
States : x(t) y(t) z(t)
Parameters : 105
Independent variable: t
Equations
Difference(t; dt=1.0, update=false)(x(t)) = p₁ + p₁₀*(y(t)^2) + p₁₅*(y(t)^4) + p₂₆*(z(t)^2) + p₂*x(t) + p₃*(x(t)^2) + p₄*(x(t)^3) + p₅*(x(t)^4) + p₁₃*(y(t)^3) + p₁₆*z(t) + p₃₂*(z(t)^3) + p₃₅*(z(t)^4) + p₆*y(t) + p₁₉*(x(t)^3)*z(t) + p₁₁*(y(t)^2)*x(t) + p₁₂*(x(t)^2)*(y(t)^2) + p₁₄*(y(t)^3)*x(t) + p₁₇*x(t)*z(t) + p₂₅*(y(t)^3)*z(t) + p₂₀*y(t)*z(t) + p₂₈*(x(t)^2)*(z(t)^2) + p₂₇*(z(t)^2)*x(t) + p₃₃*(z(t)^3)*x(t) + p₂₉*(z(t)^2)*y(t) + p₃₄*(z(t)^3)*y(t) + p₈*(x(t)^2)*y(t) + p₉*(x(t)^3)*y(t) + p₁₈*(x(t)^2)*z(t) + p₂₃*(y(t)^2)*z(t) + p₃₁*(y(t)^2)*(z(t)^2) + p₇*x(t)*y(t) + p₂₄*(y(t)^2)*x(t)*z(t) + p₂₂*(x(t)^2)*y(t)*z(t) + p₂₁*x(t)*y(t)*z(t) + p₃₀*(z(t)^2)*x(t)*y(t)
Difference(t; dt=1.0, update=false)(y(t)) = p₃₆ + p₃₈*(x(t)^2) + p₃₉*(x(t)^3) + p₄₀*(x(t)^4) + p₄₅*(y(t)^2) + p₄₈*(y(t)^3) + p₅₀*(y(t)^4) + p₃₇*x(t) + p₄₁*y(t) + p₅₁*z(t) + p₆₁*(z(t)^2) + p₆₇*(z(t)^3) + p₇₀*(z(t)^4) + p₄₆*(y(t)

27931.23

In [30]:
typeof(ddsol)

DataDrivenSolution{Float64}

In [106]:
#using Subscripts Package is not working, props gehen raus an https://github.com/HaoxuanGuo/Subscripts.jl/blob/main/src/Subscripts.jl
super_chars = ['⁰', '¹', '²', '³', '⁴', '⁵', '⁶', '⁷', '⁸', '⁹']
sub_chars = ['₀', '₁', '₂', '₃', '₄', '₅', '₆', '₇', '₈', '₉']
function recover(s::String)
    res = ""
    for c in s
        for i in 1:length(super_chars)
            if c == super_chars[i] || c == sub_chars[i]
                res *= '0' + i - 1
            end
        end
    end
    return res
end

"12"

In [154]:
ddsol.basis
ddsol.prob.p  #perfect reconstruction if we set the ridge regression penalty to 0

#ddsol.prob.p
x,y,z = ddsol.basis
a = split(string(x), "+")
a[2]

#muss für jeden String gemacht werden:
#Beobachtung: jedes p_ besitzt genau einen Term dahinter -> ich kann nach diesen Suchen und vllt die kleinen Zahlen extrahieren
# occursin("p",a[2]) true and false

#Verwendung von findall kann helfen auszuschließen, dass ausversehen mehrere p-Terme in einem Substring untergebracht sind 
#split(a[2],"*")
str = a[2]
#print(str)
#index = findall("p",str)
findall.( x -> x .== 'p', a)
#scheint IMMER an der zweiten Stelle zu sein, daraus könnte ich einen Test generieren

#ignoriere den ersten Wert erstmal - MUSS noch hinzugefügt werden!!!
n = length(a)
param = ones(n)
for i in 1:n
    if i == 1
        b = split(a[i], "~")
        s = b[2][3:end]
        var = recover(string(s))
        param_nummer = parse(Int, var)
        param[i] = ddsol.prob.p[param_nummer]
    else
        b = split(a[i], "*")
        str = b[1][3:end]
        var = recover(string(str))
        param_nummer = parse(Int, var)
        param[i] = ddsol.prob.p[param_nummer]
    end
end



param
 
#methods(x)
#sol = solve(sol.prob, Tsit5())


35-element Vector{Float64}:
  27931.23
   5692.99
    164.84
   2113.87
  -8528.05
    342.85
    -69.84
      3.82
   1421.74
 -12075.77
      ⋮
    -45.39
   -531.85
  -2753.11
    433.79
  -4958.7
    536.07
   -225.64
   2685.62
   -355.86

In [144]:
a

35-element Vector{SubString{String}}:
 "Difference(t; dt=1.0, update=false)(x(t)) ~ p₁ "
 " p₁₀*(y(t)^2) "
 " p₁₅*(y(t)^4) "
 " p₂₆*(z(t)^2) "
 " p₂*x(t) "
 " p₃*(x(t)^2) "
 " p₄*(x(t)^3) "
 " p₅*(x(t)^4) "
 " p₁₃*(y(t)^3) "
 " p₁₆*z(t) "
 ⋮
 " p₉*(x(t)^3)*y(t) "
 " p₁₈*(x(t)^2)*z(t) "
 " p₂₃*(y(t)^2)*z(t) "
 " p₃₁*(y(t)^2)*(z(t)^2) "
 " p₇*x(t)*y(t) "
 " p₂₄*(y(t)^2)*x(t)*z(t) "
 " p₂₂*(x(t)^2)*y(t)*z(t) "
 " p₂₁*x(t)*y(t)*z(t) "
 " p₃₀*(z(t)^2)*x(t)*y(t)"

In [43]:
sol = solve(ddsol.prob, Tsit5())

plot(x_sindy, idxs=[1], tspan=(0, 5), label="El Nino Data", title="on training data")
plot!(sol, idxs=[1], tspan=(0, 5), label="SINDy")

plot(x_sindy, idxs=[1], tspan=(50, 100), label="El Nino Data", title="on validation data")
plot!(sol, idxs=[1], tspan=(50, 100), label="SINDy")

MethodError: MethodError: no method matching init(::DataDrivenProblem{Float64, false, DataDrivenDiffEq.Discrete}, ::Tsit5{Static.False,…})

Some of the types have been truncated in the stacktrace for improved reading. To emit complete information
in the stack trace, evaluate `TruncatedStacktraces.VERBOSE[] = true` and re-run the code.

Closest candidates are:
  init(!Matched::PDEProblem, ::SciMLBase.AbstractDEAlgorithm, !Matched::Any...; kwargs...) at ~/.julia/packages/DiffEqBase/JH4gt/src/solve.jl:1011
  init(!Matched::OptimizationProblem, ::Any, !Matched::Any...; kwargs...) at ~/.julia/packages/SciMLBase/gTrkJ/src/solve.jl:145
  init(::DataDrivenDiffEq.AbstractDataDrivenProblem, !Matched::DataDrivenDiffEq.AbstractBasis) at ~/.julia/packages/DataDrivenDiffEq/Z5a34/src/commonsolve.jl:50
  ...